_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 100
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 100
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
architecture:
    value: simpleCNN
dataset:
    value: MNIST
epochs:
    value: 5
learning_rate:
    value: 0.0001
